language: python
cache: pip
python:
  - "2.7"
install:
  - pip install -r test-requirements.txt --upgrade
  - pip install coveralls
script:
  - nosetests -vs --with-coverage --cover-erase --cover-package=pyvtt
after_success:
  coveralls
